version: '3.8'

services:
  discord-bot:
    container_name: discord-bot
    build: .
    image: discord-bot
    restart: always
    volumes:
      - .:/home/node/app
      - ./frontend:/home/node/app/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${NETWORK_NAME}"
      - "traefik.http.routers.discord-backend-redirect.rule=Host(`${SERVER_DOMAIN}`)"
      - "traefik.http.routers.discord-backend-redirect.middlewares=redirect@file"
      - "traefik.http.routers.discord-backend.rule=Host(`${SERVER_DOMAIN}`)"
      - "traefik.http.routers.discord-backend.tls=true"
      - "traefik.http.routers.discord-frontend-redirect.rule=Host(`${CLIENT_DOMAIN}`)"
      - "traefik.http.routers.discord-frontend-redirect.middlewares=redirect@file"
      - "traefik.http.routers.discord-frontend.rule=Host(`${CLIENT_DOMAIN}`)"
      - "traefik.http.routers.discord-frontend.tls=true"
      - "traefik.http.routers.discord-backend-redirect.service=discord-backend"
      - "traefik.http.routers.discord-frontend-redirect.service=discord-frontend"
      - "traefik.http.routers.discord-backend.service=discord-backend"
      - "traefik.http.routers.discord-frontend.service=discord-frontend"
      - "traefik.http.services.discord-backend.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.services.discord-frontend.loadbalancer.server.port=${CLIENT_PORT}"
      # - "traefik.http.routers.discord-backend-redirect.rule=Host(`${SERVER_DOMAIN}`)"
      # - "traefik.http.routers.discord-backend-redirect.middlewares=redirect@file"
      # - "traefik.http.routers.discord-backend.rule=Host(`${SERVER_DOMAIN}`)"
      # - "traefik.http.routers.discord-backend.tls=true"
      # - "traefik.http.routers.discord-frontend-redirect.rule=Host(`${CLIENT_DOMAIN}`)"
      # - "traefik.http.routers.discord-frontend-redirect.middlewares=redirect@file"
      # - "traefik.http.routers.discord-frontend.rule=Host(`${CLIENT_DOMAIN}`)"
      # - "traefik.http.routers.discord-frontend.tls=true"
      # - "traefik.http.services.discord-backend.loadbalancer.server.port=${SERVER_PORT}"
      # - "traefik.http.services.discord-frontend.loadbalancer.server.port=${CLIENT_PORT}"

networks:
  default:
    external:
      name: ${NETWORK_NAME}
