export const EMOTE_LIST_REQUEST = 'EMOTE_LIST_REQUEST'
export const EMOTE_LIST_SUCCESS = 'EMOTE_LIST_SUCCESS'
export const EMOTE_LIST_FAIL = 'EMOTE_LIST_FAIL'

export const EMOTE_DETAILS_REQUEST = 'EMOTE_DETAILS_REQUEST'
export const EMOTE_DETAILS_SUCCESS = 'EMOTE_DETAILS_SUCCESS'
export const EMOTE_DETAILS_FAIL = 'EMOTE_DETAILS_FAIL'

export const EMOTE_DELETE_REQUEST = 'EMOTE_DELETE_REQUEST'
export const EMOTE_DELETE_SUCCESS = 'EMOTE_DELETE_SUCCESS'
export const EMOTE_DELETE_FAIL = 'EMOTE_DELETE_FAIL'

export const EMOTE_UPDATE_REQUEST = 'EMOTE_UPDATE_REQUEST'
export const EMOTE_UPDATE_SUCCESS = 'EMOTE_UPDATE_SUCCESS'
export const EMOTE_UPDATE_FAIL = 'EMOTE_UPDATE_FAIL'
export const EMOTE_UPDATE_RESET = 'EMOTE_UPDATE_RESET'

export const EMOTE_CREATE_REQUEST = 'EMOTE_CREATE_REQUEST'
export const EMOTE_CREATE_SUCCESS = 'EMOTE_CREATE_SUCCESS'
export const EMOTE_CREATE_FAIL = 'EMOTE_CREATE_FAIL'
export const EMOTE_CREATE_RESET = 'EMOTE_CREATE_RESET'

export const EMOTE_UPLOAD_IMAGE_REQUEST = 'EMOTE_UPLOAD_IMAGE_REQUEST'
export const EMOTE_UPLOAD_IMAGE_SUCCESS = 'EMOTE_UPLOAD_IMAGE_SUCCESS'
export const EMOTE_UPLOAD_IMAGE_FAIL = 'EMOTE_UPLOAD_IMAGE_FAIL'
export const EMOTE_UPLOAD_IMAGE_RESET = 'EMOTE_UPLOAD_IMAGE_RESET'

export const EMOTE_REVIEW_CREATE_REQUEST = 'EMOTE_REVIEW_CREATE_REQUEST'
export const EMOTE_REVIEW_CREATE_SUCCESS = 'EMOTE_REVIEW_CREATE_SUCCESS'
export const EMOTE_REVIEW_CREATE_FAIL = 'EMOTE_REVIEW_CREATE_FAIL'
export const EMOTE_REVIEW_CREATE_RESET = 'EMOTE_REVIEW_CREATE_RESET'

export const EMOTE_TOP_REQUEST = 'EMOTE_TOP_REQUEST'
export const EMOTE_TOP_SUCCESS = 'EMOTE_TOP_SUCCESS'
export const EMOTE_TOP_FAIL = 'EMOTE_TOP_FAIL'